// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/product/service.go
//
// Generated by this command:
//
//	mockgen -source=./services/product/service.go -destination=./services/product/mock/service.go
//

// Package mock_product is a generated GoMock package.
package mock_product

import (
	reflect "reflect"

	apiproduct "github.com/sendydwi/online-book-store/api/product"
	gomock "go.uber.org/mock/gomock"
)

// MockProductServiceInterface is a mock of ProductServiceInterface interface.
type MockProductServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceInterfaceMockRecorder
}

// MockProductServiceInterfaceMockRecorder is the mock recorder for MockProductServiceInterface.
type MockProductServiceInterfaceMockRecorder struct {
	mock *MockProductServiceInterface
}

// NewMockProductServiceInterface creates a new mock instance.
func NewMockProductServiceInterface(ctrl *gomock.Controller) *MockProductServiceInterface {
	mock := &MockProductServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProductServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductServiceInterface) EXPECT() *MockProductServiceInterfaceMockRecorder {
	return m.recorder
}

// GetProductById mocks base method.
func (m *MockProductServiceInterface) GetProductById(productId int) (*apiproduct.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductById", productId)
	ret0, _ := ret[0].(*apiproduct.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductById indicates an expected call of GetProductById.
func (mr *MockProductServiceInterfaceMockRecorder) GetProductById(productId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductById", reflect.TypeOf((*MockProductServiceInterface)(nil).GetProductById), productId)
}

// GetProductList mocks base method.
func (m *MockProductServiceInterface) GetProductList(page, size int) (*apiproduct.ProductListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductList", page, size)
	ret0, _ := ret[0].(*apiproduct.ProductListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductList indicates an expected call of GetProductList.
func (mr *MockProductServiceInterfaceMockRecorder) GetProductList(page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductList", reflect.TypeOf((*MockProductServiceInterface)(nil).GetProductList), page, size)
}
