services:
  database:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./deployment/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - default

  application:
    depends_on:
      - database
    restart: on-failure
    container_name: application
    build: .
    ports:
      - "80:8182"
    networks:
      - default